# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: HawkScanInstall@0
  inputs:
    version: latest
- task: RunHawkScan@0
  inputs:
    configFile: 'stackhawk-test.yml'
    version: 'latest'
  env:
    API_KEY_ENV_VAR: $(API_KEY)
    APP_HOST: https://untra.ngrok.io
